### ISSUE TITLE
Client Crashes when minimizing 

### ISSUE THREAD

**Issue by NicolaiVdS** [robertswan/diorama-game#22]
When you try to minimize the client it crashes giving this error in the CMD 
`Assertion failed: abs(aspect - std::numeric_limits<T>::epsilon()) > static_cast<T>(0), file c:\git\diorama-source\shared_third_party\glm\glm\gtc\matrix_transform.inl, line 236`

**Comment by NicolaiVdS** [comment]
only crashes when clicking the minus button ! alt+tab works fine

**Comment by robertswan** [comment]
Fixed!
